cc_library(
    name = "ui",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
        "//src/core:core",
        "//res:images",
        "//wxfb:wxfb",
    ],
    visibility = ["//visibility:public"],
)