cc_library(
    name = "render",
    hdrs = glob(["*.hpp"]),
    srcs = glob(["*.cpp"]),
    deps = [
        "//cl",
        "//src/clwrap:clwrap",
        "//src/core:core",
    ],
    visibility = ["//visibility:public"],
)