load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "aevus",
    srcs = ["aevus.cpp"],
    deps = [
        "//:lunasvg",
        "//src/ui:ui",
    ],
    visibility = ["//visibility:public"],
)